package com.jv.greendaosimple.entity;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.jv.greendaosimple.entity.Bus;
import com.jv.greendaosimple.entity.User;

import com.jv.greendaosimple.entity.BusDao;
import com.jv.greendaosimple.entity.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig busDaoConfig;
    private final DaoConfig userDaoConfig;

    private final BusDao busDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        busDaoConfig = daoConfigMap.get(BusDao.class).clone();
        busDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        busDao = new BusDao(busDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Bus.class, busDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        busDaoConfig.getIdentityScope().clear();
        userDaoConfig.getIdentityScope().clear();
    }

    public BusDao getBusDao() {
        return busDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
